#!/usr/bin/env bash
# build-factorio-skill.sh
#
# Run this from the the-reef repo root with Claude Code, ONLY when the user
# explicitly asks to refresh the reference docs.
#
# This script uses ONLY first-party Wube material: the official factorio-data
# repository (published by Wube for exactly this kind of reference use) and the
# official API JSON from lua-api.factorio.com. It never seeks out, clones, or
# fetches any independent mod author's work — that is as-needed behavior,
# executed only when the user specifically instructs it.
#
# Feeds the sources to Claude and writes three docs:
#   docs/prototype-cheatsheet.md
#   docs/space-age-api.md
#   docs/common-errors.md
# (docs/runtime-discipline.md is hand-maintained and NOT generated by this script.)
#
# Usage:
#   bash build-factorio-skill.sh
#
# Requirements: git, curl, jq, the claude CLI, internet access.

set -euo pipefail

REPO_ROOT="$(pwd)"
SCRATCH="$REPO_ROOT/.skill-scratch"
OUT="$REPO_ROOT/docs"

mkdir -p "$SCRATCH" "$OUT"

echo "=== Step 1: Clone official Wube reference data ==="

# Wube's official base + Space Age data (authoritative prototype definitions).
# This is first-party material published for modder reference — the ONLY
# repository this script touches.
if [ ! -d "$SCRATCH/factorio-data" ]; then
  git clone --depth=1 https://github.com/wube/factorio-data.git "$SCRATCH/factorio-data"
else
  echo "factorio-data already cloned, skipping."
fi

echo "=== Step 2: Gather key files ==="

# -- Wube data: planet/space-location prototypes --
WUBE_PLANETS="$SCRATCH/factorio-data/space-age/prototypes/planet"
WUBE_ENTITIES="$SCRATCH/factorio-data/space-age/prototypes/entity"
WUBE_ITEMS="$SCRATCH/factorio-data/base/prototypes/item"
WUBE_TECH="$SCRATCH/factorio-data/space-age/prototypes/technology"

# Concatenate the highest-signal Wube files into one context blob
WUBE_CONTEXT="$SCRATCH/wube-context.lua"
echo "-- WUBE OFFICIAL DATA: Planets and Space-Locations --" > "$WUBE_CONTEXT"
cat "$WUBE_PLANETS"/*.lua >> "$WUBE_CONTEXT" 2>/dev/null || true
echo "" >> "$WUBE_CONTEXT"
echo "-- WUBE OFFICIAL DATA: Thruster entity prototype --" >> "$WUBE_CONTEXT"
cat "$WUBE_ENTITIES"/thruster*.lua >> "$WUBE_CONTEXT" 2>/dev/null || true
echo "" >> "$WUBE_CONTEXT"
echo "-- WUBE OFFICIAL DATA: Asteroid entity prototypes --" >> "$WUBE_CONTEXT"
cat "$WUBE_ENTITIES"/asteroid*.lua >> "$WUBE_CONTEXT" 2>/dev/null || true
echo "" >> "$WUBE_CONTEXT"
echo "-- WUBE OFFICIAL DATA: Generator prototype --" >> "$WUBE_CONTEXT"
cat "$WUBE_ENTITIES"/generator*.lua >> "$WUBE_CONTEXT" 2>/dev/null || true
cat "$WUBE_ENTITIES"/fusion*.lua >> "$WUBE_CONTEXT" 2>/dev/null || true

echo "=== Step 3: Fetch lua-api.factorio.com key pages ==="

API_CONTEXT="$SCRATCH/factorio-api.txt"
echo "" > "$API_CONTEXT"

# The API docs are JSON-driven; fetch the runtime-api.json for the latest version.
# This is the same source FMTK uses for type definitions.
RUNTIME_API_URL="https://lua-api.factorio.com/latest/runtime-api.json"
PROTOTYPE_API_URL="https://lua-api.factorio.com/latest/prototype-api.json"

echo "Fetching runtime-api.json..."
curl -s "$RUNTIME_API_URL" -o "$SCRATCH/runtime-api.json" || echo "WARNING: could not fetch runtime-api.json"

echo "Fetching prototype-api.json..."
curl -s "$PROTOTYPE_API_URL" -o "$SCRATCH/prototype-api.json" || echo "WARNING: could not fetch prototype-api.json"

# Extract the most relevant sections using jq (events, key classes)
if command -v jq &>/dev/null && [ -f "$SCRATCH/runtime-api.json" ]; then
  echo "-- RUNTIME API: All event names and brief descriptions --" >> "$API_CONTEXT"
  jq -r '.events[] | "EVENT: \(.name)\n  \(.description // "")\n  Parameters: \([.data // [] | .[] | "\(.name): \(.type)"] | join(", "))\n"' \
    "$SCRATCH/runtime-api.json" >> "$API_CONTEXT" 2>/dev/null || true

  echo "" >> "$API_CONTEXT"
  echo "-- RUNTIME API: LuaSurface methods (relevant to platform scripting) --" >> "$API_CONTEXT"
  jq -r '.classes[] | select(.name == "LuaSurface") | .methods[] | "METHOD: LuaSurface.\(.name)\n  \(.description // "" | split("\n")[0])\n"' \
    "$SCRATCH/runtime-api.json" >> "$API_CONTEXT" 2>/dev/null || true

  echo "" >> "$API_CONTEXT"
  echo "-- RUNTIME API: LuaSpacePlatform methods --" >> "$API_CONTEXT"
  jq -r '.classes[] | select(.name == "LuaSpacePlatform") | .methods[] | "METHOD: LuaSpacePlatform.\(.name)\n  \(.description // "" | split("\n")[0])\n"' \
    "$SCRATCH/runtime-api.json" >> "$API_CONTEXT" 2>/dev/null || true
else
  echo "WARNING: jq not found or runtime-api.json missing. Skipping structured API extraction." >> "$API_CONTEXT"
  echo "Install jq (brew install jq) and re-run for better results." >> "$API_CONTEXT"
fi

if command -v jq &>/dev/null && [ -f "$SCRATCH/prototype-api.json" ]; then
  echo "" >> "$API_CONTEXT"
  echo "-- PROTOTYPE API: SpaceLocation prototype fields --" >> "$API_CONTEXT"
  jq -r '.types[] | select(.name == "SpaceLocationPrototype" or .name == "PlanetPrototype" or .name == "AsteroidPrototype" or .name == "ThrusterPrototype" or .name == "GeneratorPrototype") | "PROTOTYPE: \(.name)\nFields:\n\([.properties // [] | .[] | "  \(.name) (\(.optional // false | if . then "optional" else "required" end)): \(.type)\n    \(.description // "" | split("\n")[0])"] | join("\n"))\n"' \
    "$SCRATCH/prototype-api.json" >> "$API_CONTEXT" 2>/dev/null || true
fi

echo "=== Step 4: Feed to Claude and generate reference docs ==="

# Check Claude Code CLI is available
if ! command -v claude &>/dev/null; then
  echo "ERROR: 'claude' CLI not found. Run this script from within a Claude Code session"
  echo "or install Claude Code CLI and try again."
  exit 1
fi

# Build the combined context (truncate very large files to avoid context overflow)
COMBINED="$SCRATCH/combined-context.txt"
{
  echo "You are generating reference documentation for a Factorio Space Age mod called The Reef."
  echo "The Reef is a space-location (non-landable, like Shattered Planet), with asteroid/scrap mechanics."
  echo "It targets Factorio 2.x / Space Age, uses flib and PlanetsLib as dependencies."
  echo ""
  echo "Below is raw source material from authoritative sources. Analyze it carefully."
  echo "Do NOT rely on training data for field names, event names, or API methods — use only what appears in the source material below."
  echo ""
  echo "=== SOURCE: WUBE OFFICIAL FACTORIO DATA ==="
  head -c 100000 "$WUBE_CONTEXT"
  echo ""
  echo "=== SOURCE: FACTORIO LUA API (runtime + prototype) ==="
  head -c 100000 "$API_CONTEXT"
} > "$COMBINED"

echo "Context assembled: $(wc -c < "$COMBINED") bytes"

# --- Generate prototype-cheatsheet.md ---
echo ""
echo "Generating prototype-cheatsheet.md..."
cat "$COMBINED" | claude --print --disallowedTools Write --model claude-sonnet-4-6 "$(cat <<'PROMPT'
Using ONLY the source material provided (do not supplement with training data), generate a Markdown reference file called prototype-cheatsheet.md.

This file is a quick-lookup reference for a Factorio Space Age mod developer. It should cover exactly the prototype types used in The Reef mod:
- space-location (the destination itself)
- asteroid (scrap chunk entities)
- item (Starship Scrap, Dilithium Crystal)
- recipe
- technology
- generator (for the Dilithium Generator)
- thruster (for the Ion Thruster)
- container/inventory scripting hooks

For each prototype type, provide:
1. The exact type string used in data:extend({})
2. All required fields with their correct 2.x field names and value types
3. Common optional fields relevant to this mod
4. Any fields that changed between 1.x and 2.x / Space Age (flag these clearly)
5. One minimal working example drawn from the source material

Format as clean Markdown with a ## heading per prototype type. Be concise — this is a cheatsheet, not a tutorial. If a field name is uncertain from the source material, say so explicitly rather than guessing.

Output ONLY the raw Markdown content — no preamble, no commentary, no file write operations. The output will be captured by shell redirection.
PROMPT
)" > "$OUT/prototype-cheatsheet.md"

echo "prototype-cheatsheet.md done."

# --- Generate space-age-api.md ---
echo ""
echo "Generating space-age-api.md..."
cat "$COMBINED" | claude --print --disallowedTools Write --model claude-sonnet-4-6 "$(cat <<'PROMPT'
Using ONLY the source material provided (do not supplement with training data), generate a Markdown reference file called space-age-api.md.

This file covers Space Age-specific runtime API areas a developer of The Reef mod will use. Focus on:

1. Space platform events — list every on_space_platform_* event found in the source, with its parameter names and types
2. LuaSpacePlatform — all methods and attributes found in the source
3. Asteroid spawning — how asteroid_spawn_definitions work at runtime; any hooks for modifying spawns
4. Cross-surface item transfer — events and APIs for moving items between surfaces/platforms (cargo pods, hubs)
5. LuaSurface inventory APIs — methods for inserting/removing items from platform inventories
6. on_entity_damaged — signature and use for shield-style scripting
7. Common on_tick patterns supported by the source material

For each area: exact method/event name, parameters, return values if shown, and a one-sentence description of what it does. If something is NOT in the source material, note that explicitly — do not fill gaps with training data.

Format as clean Markdown with ## headings per area.

Output ONLY the raw Markdown content — no preamble, no commentary, no file write operations. The output will be captured by shell redirection.
PROMPT
)" > "$OUT/space-age-api.md"

echo "space-age-api.md done."

# --- Generate common-errors.md (starter, to be grown over time) ---
echo ""
echo "Generating common-errors.md..."
cat "$COMBINED" | claude --print --disallowedTools Write --model claude-sonnet-4-6 "$(cat <<'PROMPT'
Using ONLY the source material provided (do not supplement with training data), generate a Markdown reference file called common-errors.md.

This file documents API mistakes that an LLM (Claude) is likely to make when writing Factorio 2.x / Space Age mod code, based on evidence in the source material. Look for:

1. Fields that exist in 1.x but were renamed or removed in 2.x
2. Field names that look plausible but are wrong (misspellings, wrong nesting)
3. Patterns in the official data that differ from what a naive implementation might guess
4. Any explicit comments in the source code warning about common mistakes
5. Differences between the planet prototype and the space-location prototype that a developer might confuse

Format each entry as:
### [Short description of the error]
**Wrong:** `field_name_or_pattern`
**Correct:** `actual_field_name_or_pattern`
**Source:** [which file/mod this was derived from]
**Note:** [one sentence explaining why this is easy to get wrong]

If the source material doesn't give enough evidence to confirm an error pattern, omit it — do not speculate.

End with a section: ## Still Uncertain
List any field names or API calls that appear in the source but whose exact signature couldn't be confirmed from the material provided. These should be manually verified against lua-api.factorio.com.

Output ONLY the raw Markdown content — no preamble, no commentary, no file write operations. The output will be captured by shell redirection.
PROMPT
)" > "$OUT/common-errors.md"

echo "common-errors.md done."

echo ""
echo "=== Done ==="
echo "Reference files written to $OUT:"
ls -lh "$OUT/"*.md
echo ""
echo "Next steps:"
echo "  1. Review each file — correct any obvious errors before trusting them."
echo "  2. Ensure CLAUDE.md references the generated files (plus the hand-maintained runtime-discipline.md)."
echo "  3. Re-run this script (only when explicitly requested) after major Factorio updates."
echo "  4. Append to common-errors.md whenever Claude makes a Factorio-specific mistake."
echo ""
echo "Scratch data is in $SCRATCH — safe to delete once you've reviewed the output."
