-- settings.lua: mod configuration options
-- Uncomment and extend as features are added.

-- data:extend({
--   {
--     type = "double-setting",
--     name = "the-reef-dilithium-drop-rate",
--     setting_type = "startup",
--     default_value = 0.05,
--     minimum_value = 0.0,
--     maximum_value = 1.0,
--     order = "a",
--   },
-- })
