-- Icons are placeholders; replace with final art before release.

data:extend({
  { type = "fuel-category", name = "dilithium" },

  -- ── Materials (the-reef-materials row) ──────────────────────────────────

  {
    type      = "item",
    name      = "starship-scrap-chunk",
    icon      = "__space-age__/graphics/icons/metallic-asteroid-chunk.png",
    icon_size = 64,
    subgroup  = "the-reef-materials",
    order     = "a[chunk]",
    stack_size = 1,
    weight    = 100000,
  },
  {
    type      = "item",
    name      = "starship-scrap",
    icon      = "__space-age__/graphics/icons/metallic-asteroid-chunk.png",
    icon_size = 64,
    subgroup  = "the-reef-materials",
    order     = "b[scrap]",
    stack_size = 200,
  },
  {
    type      = "item",
    name      = "dilithium-crystal",
    icon      = "__space-age__/graphics/icons/promethium-asteroid-chunk.png",
    icon_size = 64,
    subgroup  = "the-reef-materials",
    order     = "c[crystal]",
    stack_size = 50,
  },
  {
    type          = "item",
    name          = "dilithium-fuel-cell",
    icon          = "__space-age__/graphics/icons/promethium-asteroid-chunk.png",
    icon_size     = 64,
    subgroup      = "the-reef-materials",
    order         = "d[fuel-cell]",
    stack_size    = 50,
    fuel_category = "dilithium",
    fuel_value    = "3GJ",
  },
  {
    type      = "tool",
    name      = "dilithium-science-pack",
    icon      = "__space-age__/graphics/icons/promethium-science-pack.png",
    icon_size = 64,
    subgroup  = "the-reef-materials",
    order     = "e[science]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
  },

  -- ── Machines (the-reef-machines row) ────────────────────────────────────

  {
    type         = "item",
    name         = "basic-pmr",
    icon         = "__space-age__/graphics/icons/shattered-planet.png",
    icon_size    = 64,
    subgroup     = "the-reef-machines",
    order        = "a[pmr]-a",
    stack_size   = 50,
    place_result = "basic-pmr",
  },
  {
    type         = "item",
    name         = "fluid-pmr",
    icon         = "__space-age__/graphics/icons/shattered-planet.png",
    icon_size    = 64,
    subgroup     = "the-reef-machines",
    order        = "a[pmr]-c",
    stack_size   = 10,
    place_result = "fluid-pmr",
  },
  {
    type         = "item",
    name         = "dilithium-reactor-1",
    icon         = "__base__/graphics/icons/nuclear-reactor.png",
    icon_size    = 64,
    subgroup     = "the-reef-machines",
    order        = "b[reactor]",
    stack_size   = 5,
    place_result = "dilithium-reactor-1",
  },
  {
    type         = "item",
    name         = "cargo-hatch",
    icon         = "__base__/graphics/icons/iron-chest.png",
    icon_size    = 64,
    subgroup     = "the-reef-machines",
    order        = "c[hatch]-a",
    stack_size   = 50,
    place_result = "cargo-hatch",
  },
  {
    type         = "item",
    name         = "advanced-cargo-hatch",
    icon         = "__base__/graphics/icons/steel-chest.png",
    icon_size    = 64,
    subgroup     = "the-reef-machines",
    order        = "c[hatch]-b",
    stack_size   = 50,
    place_result = "advanced-cargo-hatch",
  },
})
